# Write a NumPy program to implement following operation

In [1]:
# Import necessary libraries
import numpy as np

* **Convert a list of numeric values into a one-dimensional NumPy array**

In [2]:
# convert a list of numeric values into a one-dimensional NumPy array
l = [18.12, 29.5, 23.9, 100]
print("Original list = ",l)

a = np.array(l)
print("One-dimensional NumPy array: ", a)

Original list =  [18.12, 29.5, 23.9, 100]
One-dimensional NumPy array:  [ 18.12  29.5   23.9  100.  ]


* **Create a 3x3 matrix with values ranging from 2 to 10**

In [3]:
# create a 3x3 matrix with values ranging from 2 to 10
a1 = np.arange(2, 11).reshape(3, 3)
print("a1: \n", a1)

a1: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


* **Append values at the end of an array**

In [4]:
# append values at the end of an array
a = np.append(a, [11, 13])
print('Array after appending : ', a)

Array after appending :  [ 18.12  29.5   23.9  100.    11.    13.  ]


* **Create another shape from an array without changing its data(3*2 to 2*3)**

In [5]:
# to create another shape from an array without changing its data(3*2 to 2*3)
a2 = np.array([[1,2],
               [3,4],
               [5,6]])
print("a2: \n", a2)
print("Shape of a2 : ", a2.shape)

a3 = a2.reshape(2,3)
print("a3: \n", a3)
print("Shape of a3 : ", a3.shape)

a2: 
 [[1 2]
 [3 4]
 [5 6]]
Shape of a2 :  (3, 2)
a3: 
 [[1 2 3]
 [4 5 6]]
Shape of a3 :  (2, 3)
