# Write a NumPy program to implement following operation

In [1]:
# Import necessary libraries
import numpy as np

* **add, subtract, multiply, divide arguments element-wise**

In [2]:
# Create an array of eight values evenly spaced between 0 and 100
x = np.linspace(0, 100, 8, dtype="float32")
print("x : \n", x)

# Addition +
print("\nnp.add(x, 2):\n", np.add(x, 2))  

# Subtraction -
print("\nnp.subtract(x, 2):\n", np.subtract(x, 2)) 

# Multiplication *
print("\nnp.multiply(x, 2):\n", np.multiply(x, 2))

# Division /
print("\nnp.divide(x, 2):\n", np.divide(x, 2))              

x : 
 [  0.        14.285714  28.571428  42.857143  57.142857  71.42857
  85.71429  100.      ]

np.add(x, 2):
 [  2.        16.285713  30.571428  44.857143  59.142857  73.42857
  87.71429  102.      ]

np.subtract(x, 2):
 [-2.       12.285714 26.571428 40.857143 55.142857 69.42857  83.71429
 98.      ]

np.multiply(x, 2):
 [  0.        28.571428  57.142857  85.71429  114.28571  142.85715
 171.42857  200.      ]

np.divide(x, 2):
 [ 0.        7.142857 14.285714 21.428572 28.571428 35.714287 42.857143
 50.      ]


* **round elements of the array to the nearest integer**

In [3]:
print("\nnp.round(x):\n", np.round(x))


np.round(x):
 [  0.  14.  29.  43.  57.  71.  86. 100.]


* **calculate mean across dimension, in a 2D numpy array**

In [4]:
# Creating a 2x2 NumPy array
y = np.array([[18, 29], [5, 23]])
print("\nOriginal array : \n", y)

# Computing the mean of each column using axis 0 (column-wise)
print("\nMean of each column : \n", y.mean(axis=0))

# Computing the mean of each row using axis 1 (row-wise)
print("\nMean of each row : \n", y.mean(axis=1))


Original array : 
 [[18 29]
 [ 5 23]]

Mean of each column : 
 [11.5 26. ]

Mean of each row : 
 [23.5 14. ]


* **calculate the difference between neighboring elements, element-wise of a given array**

In [5]:
print("\nDifference between neighboring elements, element-wise of the y array : \n", np.diff(y))


Difference between neighboring elements, element-wise of the y array : 
 [[11]
 [18]]
