# **Write a NumPy program to implement following operation**

In [1]:
# Import necessary libraries
import numpy as np

* **to find the maximum and minimum value of a given flattened array**

In [2]:
arr = np.array([[1 ,2 ,3], [1, 2, 3], [1, 2, 3]])
print("Array before flattening : \n", arr)

a = arr.flatten()
print("\n Array after flattening : \n",a)

min = np.min(a)
print("\n Minimum value of flattern array : ",min);

max = np.max(a)
print("\n Maximum value of flattern array : ",max);

Array before flattening : 
 [[1 2 3]
 [1 2 3]
 [1 2 3]]

 Array after flattening : 
 [1 2 3 1 2 3 1 2 3]

 Minimum value of flattern array :  1

 Maximum value of flattern array :  3


* **to compute the mean, standard deviation, and variance of a given array along the second axis**

In [3]:
arr = np.array([[18,12,3],
               [29,5,7],
               [23,9,7]])
print("\nOriginal array: \n", arr)

# Calculating the mean of the array 'arr' using np.mean()
m = np.mean(arr, axis = 1)
print("\nMean : ", m)

# Calculating the standard deviation of the array 'arr' using np.std()
sd = np.std(arr, axis = 1)
print("\nStandard Deviation : ", sd)

# Calculating the variance of the array 'arr' using np.var()
v =np.var(arr, axis = 1)
print("\nVariance : ", v)



Original array: 
 [[18 12  3]
 [29  5  7]
 [23  9  7]]

Mean :  [11.         13.66666667 13.        ]

Standard Deviation :  [ 6.164414   10.87300429  7.11805217]

Variance :  [ 38.         118.22222222  50.66666667]
